### PR TITLE
Fix load order

### LINKED ISSUE #92: Reversed Load Order
When importing modules for side-effect and exporting AMD, the dependencies get loaded in the wrong order:

````js
import "foo";
import "bar";
````

Gets translated to:

````js
define(['bar', 'foo'], function () {
  'use strict';
});
````

I was expecting `['foo', 'bar']` instead, which would evaluate the modules in the original order.

### PR DESCRIPTION
**Pull request by ef4**
This closes #92. Empty imports are represented in the function arguments as `__dep0__`, `__dep1__`, etc.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good to me.

File: test/strictMode/output/umd/emptyImport.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 (function (global, factory) {
-	typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('foo'), require('polyfills')) :
-	typeof define === 'function' && define.amd ? define(['foo', 'polyfills'], factory) :
-	factory(global.bar)
-}(this, function (bar) { 'use strict';
+	typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('polyfills'), require('foo')) :
+	typeof define === 'function' && define.amd ? define(['polyfills', 'foo'], factory) :
+	factory(global.__dep0__, global.bar)
```
Comment (eventualbuddha) [inline test/strictMode/output/umd/emptyImport.js]: I believe we should pass a literal `undefined` when the import is bare to make it clearer to those reading the output, and to play it safe against accessing random properties on the global object.

Comment (ef4) [inline test/strictMode/output/umd/emptyImport.js]: Sure. In this UMD case that seems good.

For AMD I don't think we can stop the loader from passing the value of the module, but that's probably ok.

File: src/utils/mappers.js [hunk 2]
```diff
@@ -15,5 +15,9 @@ export function req ( path ) {
 }
 
 export function globalify ( name ) {
-	return 'global.' + name;
-}
\ No newline at end of file
+  	if ( /^__dep\d+__$/.test( name ) ) {
```
Comment (ef4) [inline src/utils/mappers.js]: Per @eventualbuddha 's comment I changed the UMD implementation to pass `undefined` instead of `global.__dep0__`. I did it in the least intrusive way, which is arguably hacky. A wider refactor may be better, but I lack a wider context on this codebase.

Comment (Rich-Harris) [inline src/utils/mappers.js]: I hear you. I think this is fine for now - if we ever revisit how these names are constructed (e.g. to allow for different global v local names, e.g. `global.jQuery` but `(function ($) {...`, then the refactor will happen at that point. Don't think there's any harm in the time being

**Comment by Rich-Harris** [comment]
Excellent, thanks @ef4. Released 0.6.8 with this fix
